package eu.ascetic.saas.applicationpackager.ide.wizards;

import org.eclipse.jface.wizard.IWizardPage;
import org.eclipse.jface.wizard.WizardPage;
import org.eclipse.swt.SWT;
import org.eclipse.swt.custom.StyledText;
import org.eclipse.swt.events.SelectionEvent;
import org.eclipse.swt.events.SelectionListener;
import org.eclipse.swt.layout.GridData;
import org.eclipse.swt.layout.GridLayout;
import org.eclipse.swt.widgets.Button;
import org.eclipse.swt.widgets.Composite;
import org.eclipse.swt.widgets.Display;
import org.eclipse.swt.widgets.Label;

import eu.ascetic.paas.applicationmanager.model.Application;
import eu.ascetic.saas.applicationpackager.appmanager.client.AppManagerClientHC;
import eu.ascetic.saas.applicationpackager.ide.wizards.progressDialogs.AppManagerCallProgressBarDialog;
import eu.ascetic.saas.applicationpackager.ide.wizards.progressDialogs.VmicCallProgressBarDialog;
import eu.ascetic.saas.applicationpackager.utils.Utils;

// TODO: Auto-generated Javadoc
/**
 * 
 * Copyright 2015 ATOS SPAIN S.A. 
 * 
 * Licensed under the Apache License, Version 2.0 (the License);
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 * @author David Rojo Antona. Atos Research and Innovation, Atos SPAIN SA
 * e-mail david.rojoa@atos.net 
 * 
 * This class shows the OVF response from Virtual Image Constructor
 *
 */

public class OvfResponseVmicViewerWizardPage extends WizardPage {

	/** The container. */
	private Composite container;
	
	/** The styled text. */
	private StyledText styledText;
	
	/** The called from checkbox. */
	private boolean calledFromCheckbox;
	
    private Button check;
	/**
	 * Instantiates a new ovf response vmic viewer wizard page.
	 */
	protected OvfResponseVmicViewerWizardPage() {
		super("OVF generated by ASCETiC VM Image Constructor");
		setTitle("OVF generated by ASCETiC VM Image Constructor");
		setDescription("OVF generated by ASCETiC VM Image Constructor. Next page, will send this OVF code to Application Manager");
		setControl(styledText);
	}

	/* (non-Javadoc)
	 * @see org.eclipse.jface.dialogs.IDialogPage#createControl(org.eclipse.swt.widgets.Composite)
	 */
	@Override
	public void createControl(Composite parent) {
		container = new Composite(parent, SWT.NONE);
		GridLayout layout = new GridLayout();
		container.setLayout(layout);
		layout.numColumns = 2;
//		Label label1 = new Label(container, SWT.NONE);
//		label1.setText("File");
//
//		text1 = new Text(container, SWT.BORDER | SWT.SINGLE);
//		text1.setText("");		
//
//		GridData gd = new GridData(GridData.FILL_HORIZONTAL);
//		text1.setLayoutData(gd);
//		text1.setEditable(false);		
		
		Label contentLabel = new Label(container, SWT.NONE);
		contentLabel.setText("OVF");
//		styledText = new StyledText(container, SWT.V_SCROLL | SWT.BORDER);
		styledText = new StyledText(container, SWT.MULTI | SWT.BORDER | SWT.WRAP | SWT.V_SCROLL);
		styledText.setLayoutData(new GridData(GridData.FILL_BOTH));
		String ovfContent = "";
	
		styledText.setText(ovfContent);
		styledText.setEditable(false);
//		styledText.setSize(500, 500);
//		styledText.setBounds(10, 10, 500, 500);
		
		Label labelCheck = new Label(container, SWT.NONE);
		labelCheck.setText("Continue?");
		
        check = new Button(container, SWT.CHECK);
		check.setSelection(false);check.addSelectionListener(new SelectionListener() {
			
			@Override
			public void widgetSelected(SelectionEvent arg0) {
				// TODO Auto-generated method stub
				if (check.getSelection() == true) {
					setPageComplete(true);

					calledFromCheckbox = true;
//					vmicClient.testGenerateImageWorkflow();
				}
				else {
					setPageComplete(false);
				}
			}
			
			@Override
			public void widgetDefaultSelected(SelectionEvent arg0) {
				// TODO Auto-generated method stub
				
			}
		});

		
		// required to avoid an error in the system
		setControl(container);
		setPageComplete(false);
		
	}

	/**
	 * Sets the content.
	 *
	 * @param ovfGenerated the new content
     * @param error specify if an error has happened
	 */
	public void setContent(final String ovfGenerated, final boolean error) {
		// TODO Auto-generated method stub
//		culo ovfGenerated = Utils.replaceArrow(ovfGenerated);
		Display.getDefault().asyncExec(new Runnable() {
			public void run() {
				styledText.setText(ovfGenerated);		
		        if (error){
					check.setEnabled(false);
				}
			}
		});
		
	}
	
	/* (non-Javadoc)
	 * @see org.eclipse.jface.wizard.WizardPage#getNextPage()
	 */
	@Override
	public IWizardPage getNextPage() {			
		IWizardPage nextPage = super.getNextPage();	
		if (calledFromCheckbox){
//			AppManagerClientHC appManClient = new AppManagerClientHC();
//			Application app = appManClient.postApplication(styledText.getText());
//			if (app == null){				
//				((XmlResponseAppManViewerWizardPage) nextPage).setErrorUploadingApp("ERROR retrieving XML from AppManager");	
//			}
//			else {
//				((XmlResponseAppManViewerWizardPage) nextPage).setContent(app);
//			}
			//new code
			AppManagerCallProgressBarDialog ampbd = new AppManagerCallProgressBarDialog(
					OvfResponseVmicViewerWizardPage.this.getShell(),
					this, 
					(XmlResponseAppManViewerWizardPage) nextPage, styledText.getText());
			ampbd.open();
			//end code
			
//			Application app = new Application();
//			app.setName("myApp");
//			Deployment d = new Deployment();
//			d.setStatus("SUBMITTED");
//			d.setId(1234);
//			app.addDeployment(d);
//			((XmlResponseAppManViewerWizardPage) nextPage).setContent(app);
			
			calledFromCheckbox = false;
		}	
		return nextPage;
	} 

}
