#!/bin/bash -e
  
  action=$1

  if [ "$action" == "configure" ]; then
    # Configure new version successfully installed
    newversion=$1
    echo " "
    echo " * COMPSs Successfully installed!"
    echo " "
  elif [ "$action" == "abort-remove" ]; then
    if [ $# -eq 1 ]; then
      # Generic abort remove
    else 
      # Abort remove in favour to a given package ($2=in-favour)
      package=$3
      newversion=$4
    fi
  elif [ "$action" == "abort-deconfigure" ]; then
    # $2=in-favour
    failedpackage=$3
    failedversion=$4
    if [ $# -eq 4 ];
      # Without external removals
    else
      # With removals ($5=removing)
      removedpackage=$6
      removedversion=$7
    fi
  fi

