#!/bin/bash -e
 
  action=$1

  if [ "$action" == "remove" ]; then
    if [ $# -eq 1 ]; then
      # Generic remove
    else 
      # With favour ($2=in-favour)
      package=$3
      newversion=$4
    fi
  elif [ "$action" == "upgrade" ]; then 
    # Upgrade to new version
    newversion=$2
  elif [ "$action" == "deconfigure" ]; then
    # $2=in-favour
    installedpackage=$3
    installedversion=$4
    if [ $# -eq 4 ];
      # Without external removals
    else
      # With removals ($5=removing)
      removedpackage=$6
      removedversion=$7
    fi
  elif [ "$action" == "failed-upgrade" ]; then
    # Failed upgrade
    oldversion=$3
  fi
