#!/bin/bash
  targetDir=$1
  scriptDir=$(pwd)/$(dirname $0)
  
  mkdir -p ${targetDir}
  autoreconf --force --install
  ./configure --enable-gettimeofday-clock --without-mpi --without-unwind --without-dyninst --without-papi --without-binutils --with-java=$JAVA_HOME --prefix=${targetDir} --libdir=${targetDir}/lib
  make
  make install
  if [ $? -ne 0 ]; then
    exit 1
  fi
