#!/bin/sh -e

echo " "
echo "Installing COMP Superscalar at /opt/COMPSs ..."
echo " "
echo " "
echo " * Setting COMPSs permissions..."
chmod 755 -R /opt/COMPSs/
chmod 777 -R /opt/COMPSs/Runtime/xml/

echo " "
echo " * COMPSs sucessfully installed!"
echo " "

