#!/bin/bash -e

mode=$1
COMPSS_VERSION=1.2
IT_HOME=`dirname $0`/../../../../compss/compss-rt
if [ $mode = "x86_64" ]
then
	if [ -z "$JAVA_HOME" ]
	then
		echo "Please define \$JAVA_HOME"
		exit 1
	fi
	export JAVA_LIB_DIR=$JAVA_HOME/jre/lib/amd64/server
fi

mkdir -p tmp/BUILD tmp/RPMS tmp/SOURCES/ tmp/SPECS/ tmp/SRPMS tmp/BUILDROOT
echo " "
echo "Packing compss-bindings-common bundle..."

mkdir -p tmp/compss-bindings-common-$COMPSS_VERSION/opt/COMPSs/Runtime/bindings/bindings-common

cp -rf $IT_HOME/bindings/bindings-common/* tmp/compss-bindings-common-$COMPSS_VERSION/opt/COMPSs/Runtime/bindings/bindings-common

cd tmp/
tar czf SOURCES/compss-bindings-common-$COMPSS_VERSION.tar.gz compss-bindings-common-$COMPSS_VERSION/
if [ $? -ne 0 ]; then
	echo "Error compressing package";
	exit 1;
fi
rm -rf compss-bindings-common-$COMPSS_VERSION/

echo " "
echo "Copying sources to RPM build path..."
cp ../compss-bindings-common_$mode.spec SPECS/

echo " "
echo "Generating RPM package..."
rpmbuild --define "_topdir $PWD" -bb --clean SPECS/compss-bindings-common_$mode.spec
if [ $? -ne 0 ]; then
	echo "Error compressing package";
	exit 1;
fi
echo " "
echo "Moving built RPM package to final location..."
mkdir -p ../../../../packages/rpm/compss-bindings-common
mv RPMS/$mode/compss-bindings-common-* ../../../../packages/rpm/compss-bindings-common
echo " "
cd ..
rm -r tmp/
