#!/bin/bash -e

mode=$1
COMPSS_VERSION=1.2

if [ $mode = "x86_64" ]
then
	if [ -z "$JAVA_HOME" ]
	then
		echo "Please define \$JAVA_HOME"
		exit 1
	fi
	export JAVA_LIB_DIR=$JAVA_HOME/jre/lib/amd64/server
fi

mkdir -p tmp/BUILD tmp/RPMS tmp/SOURCES/ tmp/SPECS/ tmp/SRPMS tmp/BUILDROOT
echo " "
echo "Packing COMPSs C binding bundle..."

mkdir -p tmp/compss-c-binding-$COMPSS_VERSION/opt/COMPSs/Runtime/bindings

cp -rf ../../../../compss/compss-rt/bindings/bindings-common tmp/compss-c-binding-$COMPSS_VERSION/opt/COMPSs/Runtime/bindings
cp -rf ../../../../compss/compss-rt/bindings/c tmp/compss-c-binding-$COMPSS_VERSION/opt/COMPSs/Runtime/bindings

cd tmp/
tar czf SOURCES/compss-c-binding-$COMPSS_VERSION.tar.gz compss-c-binding-$COMPSS_VERSION/
if [ $? -ne 0 ]; then
	echo "Error compressing package";
	exit 1;
fi
rm -rf compss-c-binding-$COMPSS_VERSION/

echo " "
echo "Copying sources to RPM build path..."
cp ../compss-c-binding_$mode.spec SPECS/

echo " "
echo "Generating RPM package..."
rpmbuild --define "_topdir $PWD" -bb --clean SPECS/compss-c-binding_$mode.spec
if [ $? -ne 0 ]; then
	echo "Error compressing package";
	exit 1;
fi
echo " "
echo "Moving built RPM package to final location..."
mkdir -p ../../../../packages/rpm/compss-c-binding/
mv RPMS/$mode/compss-c-binding-* ../../../../packages/rpm/compss-c-binding
echo " "
cd ..
rm -r tmp/
