/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_bsc_cepbatools_extrae_Wrapper */

#ifndef _Included_es_bsc_cepbatools_extrae_Wrapper
#define _Included_es_bsc_cepbatools_extrae_Wrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     es_bsc_cepbatools_extrae_Wrapper
 * Method:    Init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_es_bsc_cepbatools_extrae_Wrapper_Init
  (JNIEnv *, jclass);

/*
 * Class:     es_bsc_cepbatools_extrae_Wrapper
 * Method:    Fini
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_es_bsc_cepbatools_extrae_Wrapper_Fini
  (JNIEnv *, jclass);

/*
 * Class:     es_bsc_cepbatools_extrae_Wrapper
 * Method:    Event
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_es_bsc_cepbatools_extrae_Wrapper_Event
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     es_bsc_cepbatools_extrae_Wrapper
 * Method:    nEvent
 * Signature: ([I[J)V
 */
JNIEXPORT void JNICALL Java_es_bsc_cepbatools_extrae_Wrapper_nEvent
  (JNIEnv *, jclass, jintArray, jlongArray);

/*
 * Class:     es_bsc_cepbatools_extrae_Wrapper
 * Method:    defineEventType
 * Signature: (ILjava/lang/String;J[J[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_es_bsc_cepbatools_extrae_Wrapper_defineEventType
  (JNIEnv *, jclass, jint, jstring, jlong, jlongArray, jobjectArray);

/*
 * Class:     es_bsc_cepbatools_extrae_Wrapper
 * Method:    SetOptions
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_es_bsc_cepbatools_extrae_Wrapper_SetOptions
  (JNIEnv *, jclass, jint);

/*
 * Class:     es_bsc_cepbatools_extrae_Wrapper
 * Method:    Shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_es_bsc_cepbatools_extrae_Wrapper_Shutdown
  (JNIEnv *, jclass);

/*
 * Class:     es_bsc_cepbatools_extrae_Wrapper
 * Method:    Restart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_es_bsc_cepbatools_extrae_Wrapper_Restart
  (JNIEnv *, jclass);

/*
 * Class:     es_bsc_cepbatools_extrae_Wrapper
 * Method:    Comm
 * Signature: (ZIIIJ)V
 */
JNIEXPORT void JNICALL Java_es_bsc_cepbatools_extrae_Wrapper_Comm
  (JNIEnv *, jclass, jboolean, jint, jint, jint, jlong);

/*
 * Class:     es_bsc_cepbatools_extrae_Wrapper
 * Method:    GetPID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_es_bsc_cepbatools_extrae_Wrapper_GetPID
  (JNIEnv *, jclass);

/*
 * Class:     es_bsc_cepbatools_extrae_Wrapper
 * Method:    SetTaskID
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_es_bsc_cepbatools_extrae_Wrapper_SetTaskID
  (JNIEnv *, jclass, jint);

/*
 * Class:     es_bsc_cepbatools_extrae_Wrapper
 * Method:    SetNumTasks
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_es_bsc_cepbatools_extrae_Wrapper_SetNumTasks
  (JNIEnv *, jclass, jint);

/*
 * Class:     es_bsc_cepbatools_extrae_Wrapper
 * Method:    GetTaskID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_es_bsc_cepbatools_extrae_Wrapper_GetTaskID
  (JNIEnv *, jclass);

/*
 * Class:     es_bsc_cepbatools_extrae_Wrapper
 * Method:    GetNumTasks
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_es_bsc_cepbatools_extrae_Wrapper_GetNumTasks
  (JNIEnv *, jclass);

/*
 * Class:     es_bsc_cepbatools_extrae_Wrapper
 * Method:    SetThreadID
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_es_bsc_cepbatools_extrae_Wrapper_SetThreadID
  (JNIEnv *, jclass, jint);

/*
 * Class:     es_bsc_cepbatools_extrae_Wrapper
 * Method:    SetNumThreads
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_es_bsc_cepbatools_extrae_Wrapper_SetNumThreads
  (JNIEnv *, jclass, jint);

/*
 * Class:     es_bsc_cepbatools_extrae_Wrapper
 * Method:    GetThreadID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_es_bsc_cepbatools_extrae_Wrapper_GetThreadID
  (JNIEnv *, jclass);

/*
 * Class:     es_bsc_cepbatools_extrae_Wrapper
 * Method:    GetNumThreads
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_es_bsc_cepbatools_extrae_Wrapper_GetNumThreads
  (JNIEnv *, jclass);

/*
 * Class:     es_bsc_cepbatools_extrae_Wrapper
 * Method:    resumeVirtualThread
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_es_bsc_cepbatools_extrae_Wrapper_resumeVirtualThread
  (JNIEnv *, jclass, jlong);

/*
 * Class:     es_bsc_cepbatools_extrae_Wrapper
 * Method:    suspendVirtualThread
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_es_bsc_cepbatools_extrae_Wrapper_suspendVirtualThread
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
