//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.06 at 03:09:20 PM CEST 
//


package integratedtoolkit.types.project.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CloudProviderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CloudProviderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LimitOfVMs" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Property" type="{}PropertyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ImageList" type="{}imageListType"/>
 *         &lt;element name="InstanceTypes" type="{}instancesListTypes"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CloudProviderType", propOrder = {
    "limitOfVMs",
    "property",
    "imageList",
    "instanceTypes"
})
public class CloudProviderType {

    @XmlElement(name = "LimitOfVMs")
    protected Integer limitOfVMs;
    @XmlElement(name = "Property")
    protected List<PropertyType> property;
    @XmlElement(name = "ImageList", required = true)
    protected ImageListType imageList;
    @XmlElement(name = "InstanceTypes", required = true)
    protected InstancesListTypes instanceTypes;
    @XmlAttribute(name = "name", required = true)
    protected String name;

    /**
     * Gets the value of the limitOfVMs property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLimitOfVMs() {
        return limitOfVMs;
    }

    /**
     * Sets the value of the limitOfVMs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLimitOfVMs(Integer value) {
        this.limitOfVMs = value;
    }

    /**
     * Gets the value of the property property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the property property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PropertyType }
     * 
     * 
     */
    public List<PropertyType> getProperty() {
        if (property == null) {
            property = new ArrayList<PropertyType>();
        }
        return this.property;
    }

    /**
     * Gets the value of the imageList property.
     * 
     * @return
     *     possible object is
     *     {@link ImageListType }
     *     
     */
    public ImageListType getImageList() {
        return imageList;
    }

    /**
     * Sets the value of the imageList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageListType }
     *     
     */
    public void setImageList(ImageListType value) {
        this.imageList = value;
    }

    /**
     * Gets the value of the instanceTypes property.
     * 
     * @return
     *     possible object is
     *     {@link InstancesListTypes }
     *     
     */
    public InstancesListTypes getInstanceTypes() {
        return instanceTypes;
    }

    /**
     * Sets the value of the instanceTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstancesListTypes }
     *     
     */
    public void setInstanceTypes(InstancesListTypes value) {
        this.instanceTypes = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
