package net.atos.ari.seip.CloudManager.db.model;
// Generated 17-Jun-2014 11:35:53 by Hibernate Tools 3.2.2.GA



/**
 * InstanceNetwork generated by hbm2java
 */
public class InstanceNetwork  implements java.io.Serializable {


     private Integer idinstanceNetwork;
     private Leases leases;
     private IntanceInfo intanceInfo;
     private ServiceNetwork serviceNetwork;
     private String networkType;

    public InstanceNetwork() {
    }

    public InstanceNetwork(Leases leases, IntanceInfo intanceInfo, ServiceNetwork serviceNetwork, String networkType) {
       this.leases = leases;
       this.intanceInfo = intanceInfo;
       this.serviceNetwork = serviceNetwork;
       this.networkType = networkType;
    }
   
    public Integer getIdinstanceNetwork() {
        return this.idinstanceNetwork;
    }
    
    public void setIdinstanceNetwork(Integer idinstanceNetwork) {
        this.idinstanceNetwork = idinstanceNetwork;
    }
    public Leases getLeases() {
        return this.leases;
    }
    
    public void setLeases(Leases leases) {
        this.leases = leases;
    }
    public IntanceInfo getIntanceInfo() {
        return this.intanceInfo;
    }
    
    public void setIntanceInfo(IntanceInfo intanceInfo) {
        this.intanceInfo = intanceInfo;
    }
    public ServiceNetwork getServiceNetwork() {
        return this.serviceNetwork;
    }
    
    public void setServiceNetwork(ServiceNetwork serviceNetwork) {
        this.serviceNetwork = serviceNetwork;
    }
    public String getNetworkType() {
        return this.networkType;
    }
    
    public void setNetworkType(String networkType) {
        this.networkType = networkType;
    }




}


