package net.atos.ari.seip.CloudManager.db.model;
// Generated 17-Jun-2014 11:35:53 by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * InstanceStatus generated by hbm2java
 */
public class InstanceStatus  implements java.io.Serializable {


     private Integer idinstanceStatus;
     private IntanceInfo intanceInfo;
     private String instanceStatus;
     private Date time;

    public InstanceStatus() {
    }

    public InstanceStatus(IntanceInfo intanceInfo, String instanceStatus, Date time) {
       this.intanceInfo = intanceInfo;
       this.instanceStatus = instanceStatus;
       this.time = time;
    }
   
    public Integer getIdinstanceStatus() {
        return this.idinstanceStatus;
    }
    
    public void setIdinstanceStatus(Integer idinstanceStatus) {
        this.idinstanceStatus = idinstanceStatus;
    }
    public IntanceInfo getIntanceInfo() {
        return this.intanceInfo;
    }
    
    public void setIntanceInfo(IntanceInfo intanceInfo) {
        this.intanceInfo = intanceInfo;
    }
    public String getInstanceStatus() {
        return this.instanceStatus;
    }
    
    public void setInstanceStatus(String instanceStatus) {
        this.instanceStatus = instanceStatus;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }




}


