package net.atos.ari.seip.CloudManager.db.model;
// Generated 05-May-2014 15:45:16 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Leases generated by hbm2java
 */
public class Leases  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 4459243260950239377L;
	
	private Integer idleases;
     private Networks networks;
     private String ip;
     private String mac;
     private String type;
     private Set instanceNetworks = new HashSet(0);

    public Leases() {
    }

	
    public Leases(Networks networks, String ip, String mac) {
        this.networks = networks;
        this.ip = ip;
        this.mac = mac;
    }
    public Leases(Networks networks, String ip, String mac, String type, Set instanceNetworks) {
       this.networks = networks;
       this.ip = ip;
       this.mac = mac;
       this.type = type;
       this.instanceNetworks = instanceNetworks;
    }
   
    public Integer getIdleases() {
        return this.idleases;
    }
    
    public void setIdleases(Integer idleases) {
        this.idleases = idleases;
    }
    public Networks getNetworks() {
        return this.networks;
    }
    
    public void setNetworks(Networks networks) {
        this.networks = networks;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public String getMac() {
        return this.mac;
    }
    
    public void setMac(String mac) {
        this.mac = mac;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set getInstanceNetworks() {
        return this.instanceNetworks;
    }
    
    public void setInstanceNetworks(Set instanceNetworks) {
        this.instanceNetworks = instanceNetworks;
    }




}


