package net.atos.ari.seip.CloudManager.db.model;
// Generated 17-Jun-2014 11:35:53 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Networks generated by hbm2java
 */
public class Networks  implements java.io.Serializable {


     private Integer idnetworks;
     private String netwokId;
     private String serviceId;
     private String networkType;
     private String networkRange;
     private Set leaseses = new HashSet(0);
     private Set serviceNetworks = new HashSet(0);

    public Networks() {
    }

	
    public Networks(String netwokId, String serviceId, String networkType) {
        this.netwokId = netwokId;
        this.serviceId = serviceId;
        this.networkType = networkType;
    }
    public Networks(String netwokId, String serviceId, String networkType, String networkRange, Set leaseses, Set serviceNetworks) {
       this.netwokId = netwokId;
       this.serviceId = serviceId;
       this.networkType = networkType;
       this.networkRange = networkRange;
       this.leaseses = leaseses;
       this.serviceNetworks = serviceNetworks;
    }
   
    public Integer getIdnetworks() {
        return this.idnetworks;
    }
    
    public void setIdnetworks(Integer idnetworks) {
        this.idnetworks = idnetworks;
    }
    public String getNetwokId() {
        return this.netwokId;
    }
    
    public void setNetwokId(String netwokId) {
        this.netwokId = netwokId;
    }
    public String getServiceId() {
        return this.serviceId;
    }
    
    public void setServiceId(String serviceId) {
        this.serviceId = serviceId;
    }
    public String getNetworkType() {
        return this.networkType;
    }
    
    public void setNetworkType(String networkType) {
        this.networkType = networkType;
    }
    public String getNetworkRange() {
        return this.networkRange;
    }
    
    public void setNetworkRange(String networkRange) {
        this.networkRange = networkRange;
    }
    public Set getLeaseses() {
        return this.leaseses;
    }
    
    public void setLeaseses(Set leaseses) {
        this.leaseses = leaseses;
    }
    public Set getServiceNetworks() {
        return this.serviceNetworks;
    }
    
    public void setServiceNetworks(Set serviceNetworks) {
        this.serviceNetworks = serviceNetworks;
    }




}


