package net.atos.ari.seip.CloudManager.db.model;
// Generated 05-May-2014 15:45:16 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

/**
 * ServiceInfo generated by hbm2java
 */
public class ServiceInfo  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1202388643548902261L;
	
	private Integer idserviceInfo;
     private String serviceId;
     private String serviceManifest;
     private Set serviceStatuses = new HashSet(0);
     private Set serviceRealms = new HashSet(0);
     private Set intanceInfos = new HashSet(0);
     private Set serviceNetworks = new HashSet(0);

    public ServiceInfo() {
    }

	
    public ServiceInfo(String serviceId) {
        this.serviceId = serviceId;
    }
    public ServiceInfo(String serviceId, String serviceManifest, Set serviceStatuses, Set serviceRealms, Set intanceInfos, Set serviceNetworks) {
       this.serviceId = serviceId;
       this.serviceManifest = serviceManifest;
       this.serviceStatuses = serviceStatuses;
       this.serviceRealms = serviceRealms;
       this.intanceInfos = intanceInfos;
       this.serviceNetworks = serviceNetworks;
    }
   
    public Integer getIdserviceInfo() {
        return this.idserviceInfo;
    }
    
    public void setIdserviceInfo(Integer idserviceInfo) {
        this.idserviceInfo = idserviceInfo;
    }
    public String getServiceId() {
        return this.serviceId;
    }
    
    public void setServiceId(String serviceId) {
        this.serviceId = serviceId;
    }
    public String getServiceManifest() {
        return this.serviceManifest;
    }
    
    public void setServiceManifest(String serviceManifest) {
        this.serviceManifest = serviceManifest;
    }
    public Set getServiceStatuses() {
        return this.serviceStatuses;
    }
    
    public void setServiceStatuses(Set serviceStatuses) {
        this.serviceStatuses = serviceStatuses;
    }
    public Set getServiceRealms() {
        return this.serviceRealms;
    }
    
    public void setServiceRealms(Set serviceRealms) {
        this.serviceRealms = serviceRealms;
    }
    public Set getIntanceInfos() {
        return this.intanceInfos;
    }
    
    public void setIntanceInfos(Set intanceInfos) {
        this.intanceInfos = intanceInfos;
    }
    public Set getServiceNetworks() {
        return this.serviceNetworks;
    }
    
    public void setServiceNetworks(Set serviceNetworks) {
        this.serviceNetworks = serviceNetworks;
    }




}


