package net.atos.ari.seip.CloudManager.db.model;
// Generated 17-Jun-2014 11:35:53 by Hibernate Tools 3.2.2.GA



/**
 * ServiceRealm generated by hbm2java
 */
public class ServiceRealm  implements java.io.Serializable {


     private Integer idserviceRealm;
     private ServiceInfo serviceInfo;
     private String realmId;

    public ServiceRealm() {
    }

    public ServiceRealm(ServiceInfo serviceInfo, String realmId) {
       this.serviceInfo = serviceInfo;
       this.realmId = realmId;
    }
   
    public Integer getIdserviceRealm() {
        return this.idserviceRealm;
    }
    
    public void setIdserviceRealm(Integer idserviceRealm) {
        this.idserviceRealm = idserviceRealm;
    }
    public ServiceInfo getServiceInfo() {
        return this.serviceInfo;
    }
    
    public void setServiceInfo(ServiceInfo serviceInfo) {
        this.serviceInfo = serviceInfo;
    }
    public String getRealmId() {
        return this.realmId;
    }
    
    public void setRealmId(String realmId) {
        this.realmId = realmId;
    }




}


