package net.atos.ari.seip.CloudManager.db.model;
// Generated 17-Jun-2014 11:35:53 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

/**
 * ServiceNetwork generated by hbm2java
 */
public class ServiceNetwork  implements java.io.Serializable {


     private Integer idserviceNetwork;
     private ServiceInfo serviceInfo;
     private Networks networks;
     private Set instanceNetworks = new HashSet(0);

    public ServiceNetwork() {
    }

	
    public ServiceNetwork(ServiceInfo serviceInfo, Networks networks) {
        this.serviceInfo = serviceInfo;
        this.networks = networks;
    }
    public ServiceNetwork(ServiceInfo serviceInfo, Networks networks, Set instanceNetworks) {
       this.serviceInfo = serviceInfo;
       this.networks = networks;
       this.instanceNetworks = instanceNetworks;
    }
   
    public Integer getIdserviceNetwork() {
        return this.idserviceNetwork;
    }
    
    public void setIdserviceNetwork(Integer idserviceNetwork) {
        this.idserviceNetwork = idserviceNetwork;
    }
    public ServiceInfo getServiceInfo() {
        return this.serviceInfo;
    }
    
    public void setServiceInfo(ServiceInfo serviceInfo) {
        this.serviceInfo = serviceInfo;
    }
    public Networks getNetworks() {
        return this.networks;
    }
    
    public void setNetworks(Networks networks) {
        this.networks = networks;
    }
    public Set getInstanceNetworks() {
        return this.instanceNetworks;
    }
    
    public void setInstanceNetworks(Set instanceNetworks) {
        this.instanceNetworks = instanceNetworks;
    }




}


