#!/bin/bash -e 
 
  #############################################################
  # Name: buildMN
  # Description: SCRIPT FOR MareNostrum COMPSs BUILD
  # Parameters: <MN_user> MareNostrum user account. Preferable with ssh keys inserted
  #             <FullTmpPath> Tmp path on MareNostrum for deployment
  #             <FullTargetPath> Base Target Installation folder on MareNostrum
  #############################################################

  ####################
  # FUNCTIONS
  ####################
  usage() {
    echo " Usage: buildMN <MN_user> <FullTmpPath> <FullTargetPath>"
    echo " "
  }


  ####################
  # MAIN
  ####################
  # Get parameters
  if [ $# -eq 1 ]; then
    if [ "$1" == "usage" ]; then
      usage
      exit 0
    fi
  fi
  if [ $# -ne 3 ]; then
    echo "Incorrect number of parameters"
    usage
    exit 1
  fi

  # SET SCRIPT VARIABLES
  MNuser=$1
  MNtmpDir=$2
  MNtargetDir=$3
  scriptDir=$(pwd)/$(dirname $0)
  sourcesDir=$(pwd)/$(dirname $0)/..
  tmpDir=${scriptDir}/tmp

  echo "- MN user       = ${MNuser}"
  echo "- MN tmp Dir    = ${MNtmpDir}"
  echo "- MN target Dir = ${MNtargetDir}"
  echo "- Script Dir    = ${scriptDir}"
  echo "- Sources Dir   = ${sourcesDir}"
  echo "- Local tmp Dir = ${tmpDir}"
  sleep 5

  # COPY TRUNK
  echo "- Copy trunk to tmpdir"
  rm -rf ${tmpDir}
  mkdir -p ${tmpDir}
  cp ${sourcesDir}/changelog ${tmpDir}
  cp -r ${sourcesDir}/compss ${tmpDir}
  cp -r ${sourcesDir}/dependencies ${tmpDir}
  cp -r ${sourcesDir}/doc ${tmpDir}
  cp -r ${sourcesDir}/files ${tmpDir}
  cp ${sourcesDir}/LICENSE ${tmpDir}
  cp ${sourcesDir}/NOTICE ${tmpDir}
  cp ${sourcesDir}/pom.xml ${tmpDir}
  cp ${sourcesDir}/README ${tmpDir}
  cp ${sourcesDir}/RELEASE_NOTES ${tmpDir}
  find . -name .svn | xargs rm -rf  #Cleans svn files

  # COMPILE
  echo "- Compile sources"
  cd ${tmpDir}/compss/
  mvn clean package
  cd ${scriptDir}

  # COMPSs Monitor APACHE
  echo "- Downloading Apache for COMSPs Monitor"
  cd ${tmpDir}
  TOMCAT_VER="`curl http://ftp.cixug.es/apache/tomcat/tomcat-7/ | grep "v7" | tail -1 | awk '{print $5}' | cut -c 18-23`"
  TOMCAT_URL="http://ftp.cixug.es/apache/tomcat/tomcat-7/v$TOMCAT_VER/bin/apache-tomcat-${TOMCAT_VER}.tar.gz"
  wget ${TOMCAT_URL}
  mv apache-tomcat-${TOMCAT_VER}.tar.gz apache-tomcat.tar.gz
  cd ${scriptDir}

  # DEPLOY ON TMP MN
  echo "- Deploy files to tmpDir in MN"
  ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no ${MNuser}@mn1.bsc.es "rm -rf ${MNtmpDir}; mkdir -p ${MNtmpDir}"
  scp -r -q -o StrictHostKeyChecking=no ${tmpDir} ${MNuser}@mn1.bsc.es:${MNtmpDir}
  scp -r -q -o StrictHostKeyChecking=no ${scriptDir}/buildMN_aux ${MNuser}@mn1.bsc.es:${MNtmpDir}

  # Execute deployment aux script
  echo "- Execute installation on MN"
  ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no ${MNuser}@mn1.bsc.es "/bin/bash ${MNtmpDir}/buildMN_aux ${MNtargetDir}"

  # ERASE TMP FILES
  echo "- Erase tmp files"
  ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no ${MNuser}@mn1.bsc.es "rm -rf ${MNtmpDir}"
  rm -rf ${tmpDir}

  # END
  echo "Congratulations!"
  echo "COMPSs Runtime Successfully installed!"
  echo " "
  exit 0
