//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 05:50:58 PM CEST 
//


package integratedtoolkit.types.resources.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OSTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OSTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Linux"/>
 *     &lt;enumeration value="WindowsXP"/>
 *     &lt;enumeration value="WindowsVista"/>
 *     &lt;enumeration value="Windows7"/>
 *     &lt;enumeration value="Windows"/>
 *     &lt;enumeration value="Mac OS X"/>
 *     &lt;enumeration value="FreeBSD"/>
 *     &lt;enumeration value="SunOS"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "OSTypeType")
@XmlEnum
public enum OSTypeType {

    @XmlEnumValue("Linux")
    LINUX("Linux"),
    @XmlEnumValue("WindowsXP")
    WINDOWS_XP("WindowsXP"),
    @XmlEnumValue("WindowsVista")
    WINDOWS_VISTA("WindowsVista"),
    @XmlEnumValue("Windows7")
    WINDOWS_7("Windows7"),
    @XmlEnumValue("Windows")
    WINDOWS("Windows"),
    @XmlEnumValue("Mac OS X")
    MAC_OS_X("Mac OS X"),
    @XmlEnumValue("FreeBSD")
    FREE_BSD("FreeBSD"),
    @XmlEnumValue("SunOS")
    SUN_OS("SunOS");
    private final String value;

    OSTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OSTypeType fromValue(String v) {
        for (OSTypeType c: OSTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
