/**
 *
 *   Copyright 2014-2015 Barcelona Supercomputing Center (www.bsc.es) All rights reserved.
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.13 at 02:42:04 PM CEST 
//


package integratedtoolkit.types.resources.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for osType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="osType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OSType" type="{}OSTypeType"/>
 *         &lt;element name="PhysicalMemory" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="VirtualMemory" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="MaxProcessesPerUser" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "osType", propOrder = {
    "osType",
    "physicalMemory",
    "virtualMemory",
    "maxProcessesPerUser"
})
public class OsType {

    @XmlElement(name = "OSType", required = true)
    protected OSTypeType osType;
    @XmlElement(name = "PhysicalMemory")
    protected Float physicalMemory;
    @XmlElement(name = "VirtualMemory")
    protected Float virtualMemory;
    @XmlElement(name = "MaxProcessesPerUser")
    protected Integer maxProcessesPerUser;

    /**
     * Gets the value of the osType property.
     * 
     * @return
     *     possible object is
     *     {@link OSTypeType }
     *     
     */
    public OSTypeType getOSType() {
        return osType;
    }

    /**
     * Sets the value of the osType property.
     * 
     * @param value
     *     allowed object is
     *     {@link OSTypeType }
     *     
     */
    public void setOSType(OSTypeType value) {
        this.osType = value;
    }

    /**
     * Gets the value of the physicalMemory property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getPhysicalMemory() {
        return physicalMemory;
    }

    /**
     * Sets the value of the physicalMemory property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setPhysicalMemory(Float value) {
        this.physicalMemory = value;
    }

    /**
     * Gets the value of the virtualMemory property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getVirtualMemory() {
        return virtualMemory;
    }

    /**
     * Sets the value of the virtualMemory property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setVirtualMemory(Float value) {
        this.virtualMemory = value;
    }

    /**
     * Gets the value of the maxProcessesPerUser property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxProcessesPerUser() {
        return maxProcessesPerUser;
    }

    /**
     * Sets the value of the maxProcessesPerUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxProcessesPerUser(Integer value) {
        this.maxProcessesPerUser = value;
    }

}
