/**
 *
 *   Copyright 2014-2015 Barcelona Supercomputing Center (www.bsc.es) All rights reserved.
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.13 at 02:42:04 PM CEST 
//


package integratedtoolkit.types.resources.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OSTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OSTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Linux"/>
 *     &lt;enumeration value="WindowsXP"/>
 *     &lt;enumeration value="WindowsVista"/>
 *     &lt;enumeration value="Windows7"/>
 *     &lt;enumeration value="Windows"/>
 *     &lt;enumeration value="Mac OS X"/>
 *     &lt;enumeration value="FreeBSD"/>
 *     &lt;enumeration value="SunOS"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "OSTypeType")
@XmlEnum
public enum OSTypeType {

    @XmlEnumValue("Linux")
    LINUX("Linux"),
    @XmlEnumValue("WindowsXP")
    WINDOWS_XP("WindowsXP"),
    @XmlEnumValue("WindowsVista")
    WINDOWS_VISTA("WindowsVista"),
    @XmlEnumValue("Windows7")
    WINDOWS_7("Windows7"),
    @XmlEnumValue("Windows")
    WINDOWS("Windows"),
    @XmlEnumValue("Mac OS X")
    MAC_OS_X("Mac OS X"),
    @XmlEnumValue("FreeBSD")
    FREE_BSD("FreeBSD"),
    @XmlEnumValue("SunOS")
    SUN_OS("SunOS");
    private final String value;

    OSTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OSTypeType fromValue(String v) {
        for (OSTypeType c: OSTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
