#!/bin/bash -e

mode=$1
COMPSS_VERSION=1.2
IT_HOME=`dirname $0`/../../../../compss/compss-rt
if [ $mode = "x86_64" ]
then
	if [ -z "$JAVA_HOME" ]
	then
		echo "Please define \$JAVA_HOME"
		exit 1
	fi
	export JAVA_LIB_DIR=$JAVA_HOME/jre/lib/amd64/server
fi

mkdir -p tmp/BUILD tmp/RPMS tmp/SOURCES/ tmp/SPECS/ tmp/SRPMS tmp/BUILDROOT
echo " "
echo "Packing compss-extrae bundle..."

mkdir -p tmp/compss-extrae-$COMPSS_VERSION/opt/COMPSs/extrae/sources

cp -r $IT_HOME/../../files/extrae/* tmp/compss-extrae-$COMPSS_VERSION/opt/COMPSs/extrae/sources
cp -r $IT_HOME/../../files/paraver/cfgs tmp/compss-extrae-$COMPSS_VERSION/opt/COMPSs/extrae/sources
rm -rf tmp/compss-extrae-$COMPSS_VERSION/opt/COMPSs/extrae/sources/cfgs/.svn

cd tmp/
tar czf SOURCES/compss-extrae-$COMPSS_VERSION.tar.gz compss-extrae-$COMPSS_VERSION/
if [ $? -ne 0 ]; then
	echo "Error compressing package";
	exit 1;
fi
rm -rf compss-extrae-$COMPSS_VERSION/

echo " "
echo "Copying sources to RPM build path..."
cp ../compss-extrae_$mode.spec SPECS/

echo " "
echo "Generating RPM package..."
rpmbuild --define "_topdir $PWD" -bb --clean SPECS/compss-extrae_$mode.spec
if [ $? -ne 0 ]; then
	echo "Error compressing package";
	exit 1;
fi
echo " "
echo "Moving built RPM package to final location..."
mkdir -p ../../../../packages/rpm/compss-extrae
mv RPMS/$mode/compss-extrae-* ../../../../packages/rpm/compss-extrae
echo " "
cd ..
rm -r tmp/
