#!/bin/bash -e
  #Get parameters
  vm_ip=$1
  vm_user=$2
  log_folder=$3
  tests_status=$4

  #---------------------------------------------------------------------------------------------------------------------
  echo -e "\e[0m"
  echo "***************************"
  echo "*** Tests Post-Process  ***"
  echo "***************************"
  echo -e "\e[0m"

  #Get logs
  scp -r -o StrictHostKeyChecking=no ${vm_user}@${vm_ip}:/home/${vm_user}/tests/logs ${log_folder}

  #Clean logs
  ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no ${vm_user}@${vm_ip} "rm -rf /home/${vm_user}/tests"
  ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no ${vm_user}@${vm_ip} "rm -rf /home/${vm_user}/.COMPSs"
  ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no ${vm_user}@${vm_ip} "rm -rf /home/${vm_user}/.m2"

  #Clean history
  ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no ${vm_user}@${vm_ip} "rm -f /home/${vm_user}/.bash_history"
 
  #Prepare machine for snapshot (if needed)
  if [ "${tests_status}" == "ok" ]; then
    ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no ${vm_user}@${vm_ip} "sudo rm -f /home/${vm_user}/.ssh/known_hosts"
    ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no ${vm_user}@${vm_ip} "sudo rm -f /etc/resolv.conf"  
    ssh -t -t -o StrictHostKeyChecking=no -o BatchMode=yes -o ChallengeResponseAuthentication=no ${vm_user}@${vm_ip} "sudo rm -f /home/${vm_user}/.ssh/authorized_keys"
  fi

  #All process OK. Exit
  exit 0

